version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5003:5003"
    volumes:
      - ./backend/data:/usr/src/app/data
    environment:
      - NODE_ENV=development
      - PORT=5003
      - DB_PATH=/usr/src/app/data/database.sqlite


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend