# This is a Docker Compose file that defines services for a full-stack application.
services:
  backend:
    extends:
      file: ./backend/docker-compose.yml
      service: backend

  frontend:
    extends:
      file: ./frontend/docker-compose.yml
      service: frontend

networks:
  app-network:
    driver: bridge