
services:
  backend:
  
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:/usr/src/app/prisma/dev.db
    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    driver: bridge