global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'containers-uptime'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://logstash:9600
          - http://kibana:5601
          - https://es01:9200
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115



  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
